default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  port: 5432
  username: elenaprohorova
  password: 'password'

development:
  <<: *default
  database: news_api_new_development

#test:
#  <<: *default
#  database: news_api_test
